sudo: required
services:
  - docker

before_install:
  - docker build -t uday0802/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run uday0802/multi-docker npm test -- --coverage

after_success:
  - docker build -t uday0802/multi-client ./client
  - docker build -t uday0802/multi-nginx ./nginx
  - docker build -t uday0802/multi-server ./server
  - docker build -t uday0802/multi-worker ./worker

# login to docker
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push uday0802/multi-client
  - docker push uday0802/multi-nginx
  - docker push uday0802/multi-server
  - docker push uday0802/multi-worker