sudo: required
services:
  - docker

before_install:
  - docker build -t uday0802/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run uday0802/react-test npm test -- --coverage

after_success:
  - docker build -t uday0802/multi-client ./client
  - docker build -t uday0802/multi-nginx ./nginx
  - docker build -t uday0802/multi-server ./server
  - docker build -t uday0802/multi-worker ./worker

# login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
# push images to docker hub
  - docker push uday0802/multi-client
  - docker push uday0802/multi-nginx
  - docker push uday0802/multi-server
  - docker push uday0802/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-638145639107
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY